In [ ]:
dataset = open('day10.txt').read().split('\n')

# Question 1

In [630]:
cycle_list = list()
cycle_list.append(1)
for cycle in dataset:
    if cycle == 'noop':
        cycle_list.append(0)
    if cycle.split()[0] == 'addx':
        value = cycle.split()[1]
        cycle_list.extend([0,int(value)])
        
answer_sum = 0
quantile = [20,60,100,140,180,220]
for quant in quantile:
    answer = sum(cycle_list[:quant])*quant
    answer_sum = answer_sum + answer
answer_sum

12740

# Question 2

In [528]:
i = 0
total_sum = 0
total_sum_array = list()
for g in cycle_list:
    total_sum = total_sum + int(cycle_list[i])
    total_sum_array.append(total_sum)
    i = i + 1

In [666]:
cpt = np.zeros((40))
i = 0
l = 0
for g in cpt:
    strife = total_sum_array[i]
    strife_array = [strife-1,strife,strife+1]
    if l in strife_array:
        cpt[l] = 1
    i = i + 1
    l = l + 1

In [643]:
cpt_1 = np.zeros((40))
i = 40
l = 0
for g in cpt_1:
    strife = total_sum_array[i]
    strife_array = [strife-1,strife,strife+1]
    if l in strife_array:
        cpt_1[l] = 1
    i = i + 1
    l = l + 1

In [644]:
cpt_2 = np.zeros((40))
i = 80
l = 0
for g in cpt_2:
    strife = total_sum_array[i]
    strife_array = [strife-1,strife,strife+1]
    if l in strife_array:
        cpt_2[l] = 1
    
    i = i + 1
    l = l + 1

In [645]:
cpt_3 = np.zeros((40))
i = 120
l = 0
for g in cpt_3:
    strife = total_sum_array[i]
    strife_array = [strife-1,strife,strife+1]
    if l in strife_array:
        cpt_3[l] = 1
    
    i = i + 1
    l = l + 1

In [646]:
cpt_4 = np.zeros((40))
i = 160
l = 0
for g in cpt_4:
    strife = total_sum_array[i]
    strife_array = [strife-1,strife,strife+1]
    if l in strife_array:
        cpt_4[l] = 1
    
    i = i + 1
    l = l + 1

In [647]:
cpt_5 = np.zeros((40))
i = 200
l = 0
for g in cpt_5:
    strife = total_sum_array[i]
    strife_array = [strife-1,strife,strife+1]
    if l in strife_array:
        cpt_5[l] = 1
    
    i = i + 1
    l = l + 1

In [665]:
total_cpt = list()
total_cpt.append(cpt)
total_cpt.append(cpt_1)
total_cpt.append(cpt_2)
total_cpt.append(cpt_3)
total_cpt.append(cpt_4)
total_cpt.append(cpt_5)

In [664]:
pd.set_option('display.max_columns', None)
pd.DataFrame(total_cpt)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0
1,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
3,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0